gnssrtk:
  ros__parameters:
    debug: 0
    device: /dev/ttyACM0
    frame_id: gnss
    ntrip_client:
      ntrip_user: kde1054@naver.com
      ntrip_password: gnss
      ntrip_server: www.gnssdata.or.kr
      ntrip_port: 2101
      mount_point: TEGN-RTCM32

    publish:
      nav: false
      imu: false
      # navpvt: false